services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: imtihon-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - content-hub
    db:
        image: postgres:15
        container_name: imtihon-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5436:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - content-hub

    nginx:
        image: nginx:alpine
        container_name: imtihon-nginx
        ports:
            - "8082:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - content-hub

volumes:
    pgdata:

networks:
    content-hub:
